import React, { useState } from 'react';
import { useNavigate } from 'react-router';

import useErrorStore from '../../Store/errorStore';
import handleApiError from '../../Utils/apiError';
import { authClient } from '../../lib/auth-client';

// 💡 Ensure this path matches your auth client setup

export default function Verify2FA() {
    const [code, setCode] = useState('');
    const setError = useErrorStore((state) => state.setError);
    const error = useErrorStore((state) => state.error);
    //const [error, setError] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const navigate = useNavigate();

    const handleVerify = async (e: React.FormEvent) => {
        e.preventDefault();
        setError(null);
        setIsLoading(true);

        try {
            // 💡 Better Auth's official method to submit the 6-digit code
            const { error: authError } = await authClient.twoFactor.verifyTotp({
                code: code.trim(),
                trustDevice: true, // Optional: Remembers this browser so they don't type it every single time
            });

            if (authError) {
                setError(authError.message || 'Invalid or expired 2FA code.');
                setIsLoading(false);
                return;
            }

            // Success! The temporary lock is lifted. Send them into the admin panel
            navigate('/admin/');
        } catch (err) {
            setError('Something went wrong. Please try again.');
            handleApiError(err, setError);
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="flex min-h-screen items-center justify-center bg-[#FAF9F5] px-4">
            <div className="w-full max-w-md rounded-2xl border border-[#EBE9E0] bg-white p-8 shadow-sm">
                {/* Header */}
                <div className="mb-6 text-center">
                    <h2 className="text-2xl font-bold tracking-tight text-gray-900">
                        FreshDrop Security
                    </h2>
                    <p className="mt-2 text-sm text-gray-500">
                        Enter the 6-digit code generated by your Authenticator
                        app to access your account.
                    </p>
                </div>

                {/* Error Banner */}
                {error && (
                    <div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-center text-sm font-medium text-red-600">
                        ⚠️ {error}
                    </div>
                )}

                {/* Form */}
                <form onSubmit={handleVerify} className="space-y-4">
                    <div>
                        <label className="mb-2 block text-xs font-bold tracking-wider text-gray-700 uppercase">
                            Verification Code
                        </label>
                        <input
                            type="text"
                            maxLength={6}
                            placeholder="000000"
                            value={code}
                            onChange={(e) =>
                                setCode(e.target.value.replace(/\D/g, ''))
                            } // Strips non-numbers automatically
                            className="w-full rounded-xl border border-[#EBE9E0] p-3 text-center font-mono text-2xl tracking-[0.5em] transition-all focus:border-transparent focus:ring-2 focus:ring-[#1B4332] focus:outline-none"
                            required
                            autoFocus
                        />
                    </div>

                    <button
                        type="submit"
                        disabled={isLoading || code.length !== 6}
                        className="flex w-full items-center justify-center rounded-xl bg-[#1B4332] p-3 font-medium text-white shadow-sm transition-all hover:bg-[#133024] disabled:cursor-not-allowed disabled:opacity-50"
                    >
                        {isLoading ? 'Verifying...' : 'Verify & Continue'}
                    </button>
                </form>

                {/* Optional Fallback Link */}
                <div className="mt-6 text-center">
                    <button
                        onClick={() => navigate('/login')}
                        className="text-xs font-medium text-gray-400 transition-colors hover:text-gray-600"
                    >
                        ← Back to Login
                    </button>
                </div>
            </div>
        </div>
    );
}
